### ISSUE TITLE
Afflictions/Hazards

### ISSUE THREAD

**Issue by sigrunixia** [Obsidian-TTRPG-Community/Pathfinder-1E-SRD-Markdown#6]
> - [x] Corruptions
> - [x] Curses
> - [x] Diseases
> - [x] Drugs
> - [x] Haunts
> - [x] Madness
> - [x] Poisons
> - [x] Traps

**Comment by Craftidore** [comment]
Can't seem to mark checkboxes anymore, but Haunts are done now too

**Comment by Craftidore** [comment]
Weirdly, I was able to before. It was just today that I no longer could.

**Comment by Craftidore** [comment]
All afflictions & hazards have been completed. There's some final clean-up work I'm gonna do before I PR though.
