### ISSUE TITLE
3.5 tag

### ISSUE THREAD

**Issue by Craftidore** [Obsidian-TTRPG-Community/Pathfinder-1E-SRD-Markdown#8]
Some of the stuff in the SRD is tagged with a `3.5` image, which the tooltip says is '3.5 Material'. 

![2023-05-07-180111_172x156_scrot](https://user-images.githubusercontent.com/73705352/236707107-e53ba091-2566-410a-8aab-0a53da53c5e8.png)
![2023-05-07-181039_493x279_scrot](https://user-images.githubusercontent.com/73705352/236707129-bdbfa1f2-cae3-4326-a85a-c93b9bc1c144.png)

It's an image though, and I'm pretty sure we're not supposed to reuse any images in the SRD. We could just write `3.5` but that won't get a tooltip. 

As such, I propose creating a `3.5` note that says that this material is 3.5e D&D material, then link to that note wherever we see the `3.5` image as we convert the SRD.

**Comment by sigrunixia** [comment]
Mmm, how about we treat it like a footnote? Same for the PFS stuff.

Then we can also check https://archive.org/download/dnd35srd to see what images are in there.
